# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v-ubqzo4qtILSrk_2xAYZSHIFZ0riCpz
"""

x={"Akshay kumar":1,"Anirudh":2,"Abhilash":3}
len(x)

