# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v-ubqzo4qtILSrk_2xAYZSHIFZ0riCpz
"""

s1={"one":1,"two":2,"three":3}
s2={"four":4,"five":5}
s1.update(s2)
print("After concatination")
print(s1)

