# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v-ubqzo4qtILSrk_2xAYZSHIFZ0riCpz
"""

a={"one":1,"two":2,"three":3}
x=sum(a.values())
print(x)

