# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v-ubqzo4qtILSrk_2xAYZSHIFZ0riCpz
"""

sample={"dad":1,"mom":2,"three":3}
x=sample.pop("dad")
print(x)
print(sample.popitem())
print("after removing",sample)

