# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v-ubqzo4qtILSrk_2xAYZSHIFZ0riCpz
"""

a={"one":1,"two":2,"three":3}
x=a["one"]
y=a["two"]
z=a["three"]
print(x,y,z)